Automattic/themes-workspace

varya/assets/css/style-editor.css
varya/assets/css/variables-editor.css
varya/assets/sass/abstracts/_mixins.scss
varya/assets/sass/base/_editor.scss
varya/assets/sass/blocks/blog-posts/_editor.scss
varya/assets/sass/blocks/button/_editor.scss
varya/assets/sass/blocks/cover/_editor.scss
varya/assets/sass/blocks/gallery/_editor.scss
varya/assets/sass/blocks/group/_editor.scss
varya/assets/sass/blocks/heading/_editor.scss
varya/assets/sass/blocks/image/_editor.scss
varya/assets/sass/blocks/latest-comments/_editor.scss
varya/assets/sass/blocks/latest-posts/_editor.scss
varya/assets/sass/blocks/legacy/_editor.scss
varya/assets/sass/blocks/list/_editor.scss
varya/assets/sass/blocks/paragraph/_editor.scss
varya/assets/sass/blocks/posts-list/_editor.scss
varya/assets/sass/blocks/pullquote/_editor.scss
varya/assets/sass/blocks/quote/_editor.scss
varya/assets/sass/blocks/separator/_editor.scss
varya/assets/sass/blocks/table/_editor.scss
varya/assets/sass/blocks/utilities/_editor.scss
varya/assets/sass/child-theme/variables-editor.css
varya/default-style/functions.php
varya/functions.php

We should be using [the standard way](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#editor-styles) of enqueing the block editor stylesheets: `add_editor_style`. 
I'm not sure why Varya was using `enqueue_block_editor_assets` originally, but I'm not noticing any obvious issues swapping between this PR and the original one — the editor looks identical. 
Assuming there's no other technical limitation that requires use of `enqueue_block_editor_assets`, this just needs a little testing to ensure it's bringing in all the appropriate stylesheets still.

[Varya] Switch to using add_editor_style to enqueue block editor stylesheets.

---

varya/assets/css/style-editor.css
varya/assets/css/style-woocommerce-rtl.css
varya/assets/css/style-woocommerce.css
varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/abstracts/_config.scss
varya/assets/sass/base/_editor.scss
varya/assets/sass/blocks/blog-posts/_editor.scss
varya/assets/sass/blocks/group/_editor.scss
varya/assets/sass/blocks/media-text/_editor.scss
varya/assets/sass/blocks/utilities/_editor.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/structure/_responsive-logic.scss
varya/assets/sass/style-editor.scss
varya/style-rtl.css
varya/style.css

- Optimizes the editor styles to remove a bunch of structural, header and footer rules that aren’t relevant for the editor. 
- Fixes the editor selectors so that the correct line-height for `--global--line-height-body` value is applied.
- Fixes a small typo that broke responsive styles on larger screens.
Before:
After:

Varya: Fix line-heights in editor and optimize editor stylesheet.

---

varya/assets/css/style-woocommerce-rtl.css
varya/assets/css/style-woocommerce.css
varya/assets/css/variables.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/header/_config.scss
varya/assets/sass/components/header/_header-branding.scss
varya/assets/sass/structure/_vertical-margins.scss
varya/functions.php
varya/style-rtl.css
varya/style.css

(This is based on #21, so that should get merged in first)
Adds a few quick styles to get the site header looking more like the comps: 
- Center-aligns the items in there.
- Adjust the vertical margins.
- Adds a circular mask to the site logo.
- Changes the font weight for the header to Bold. 
- Switches the underline approach to use borders. We'll want to make this a little cleaner, but this is decent for now. 
---
Before:
After:

[Varya] Update site header styles

---

varya/assets/css/variables.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/header/_config.scss
varya/assets/sass/components/header/_primary-navigation.scss
varya/style-rtl.css
varya/style.css

This doesn't match the comps for now, but it gets things synced up with #26 until we can implement the other way. 
---
**Before**
**After**

Varya: Move main nav to the center on larger screens

---

varya/assets/sass/components/entry/_meta.scss
varya/inc/template-tags.php
varya/style-rtl.css
varya/style.css
varya/template-parts/content/content-single.php

This PR addresses removes underlines on meta links and addresses #27 
**Before**:
**After**:

[Varya] Update post meta

---

varya/assets/css/style-editor.css
varya/assets/sass/base/_editor.scss

Gutenberg injects a style rule that limits the max-width of blocks that are not align full or align wide to 580px: https://github.com/WordPress/gutenberg/blob/34253056f822cf554437d5ad449b033d811e199f/packages/edit-post/src/style.scss#L104
This causes inconsistency between the front-end and editor in this theme.
This PR leverages the responsive rules developed for the front end into the editor to set the default content width of blocks that are not align full or align wide. 
**Before**
**After**
If this approach is acceptable, then we should probably revisit how we implement the align wide responsive styles in the editor.

[Varya] Rework max width for content blocks in the editor

---

varya/assets/css/style-editor.css
varya/assets/css/style-woocommerce-rtl.css
varya/assets/css/style-woocommerce.css
varya/assets/sass/structure/_responsive-logic.scss
varya/style-rtl.css
varya/style.css

This PR revises the responsive logic to do the following:
- Remove CSS-variable based media queries in favor or normal media queries
- Remove duplicate CSS-variables
- Fix errors and typos in responsive width rules
Before | After
------------|------------
Fixes: #36

Varya: Clean up responsive logic

---

varya/assets/sass/components/header/_primary-navigation.scss
varya/style-rtl.css
varya/style.css

This removes the "-" indents for subnav items, and replaces it with some standard empty indents. Aside from just its use in this theme, using empty space seems like a more usual default scenario anyway. 
Before:
After:

Varya: Remove subnav character indents and replace with more straightforward spacing.

---

varya/assets/sass/components/header/_header-branding.scss
varya/style-rtl.css
varya/style.css

This PR adjusts the site title underline to avoid descenders, addressing this [issue](https://github.com/Automattic/themes-workspace/projects/1#card-35496673).  It uses `background-image` to draw the underline, based on [this reference](https://css-tricks.com/styling-underlines-web/). 
**Before:**
**After**
The tricky part is getting the text-shadows in balance with the "line-height"

[Varya] Refine site title underline

---

varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/abstracts/_config.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/entry/_config.scss
varya/assets/sass/components/entry/_meta.scss
varya/assets/sass/components/pagination/_style.scss
varya/style-rtl.css
varya/style.css

This takes care of a few miscellaneous things: 
- Adjusts the `--global--font-size-sm` font size from `15px` to `16px` to match the comps. 
- Removes bold weight from the post navigation. 
- Makes the post meta font size smaller to match the comps.
- Adjusts the spacing of the post footer to match the comps, adds a top border. 
---
Before: 
After:

Varya: Minor font + entry footer cleanup

---

varya/assets/css/variables.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/header/_config.scss
varya/assets/sass/components/header/_header-branding.scss
varya/assets/sass/components/header/_primary-navigation.scss
varya/functions.php
varya/style-rtl.css
varya/style.css

This PR just does some very minor header adjustments to sync up better with the original design comps. 
- Changes the site logo size to 120x120 instead of 128x128 (Whoops)
- Moves the site description up just a bit, and moves the menu down just a bit. 
---
Before: 
After:
Comparison:

Varya: Minor header cleanup

---

varya/assets/css/variables.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/header/_config.scss
varya/assets/sass/components/header/_header-branding.scss
varya/assets/sass/structure/_vertical-margins.scss
varya/style-rtl.css
varya/style.css

This PR tackles a few small cleanup tasks for the site header on small screens: 
- It implements a slightly smaller font size for the site title. 
- It adds a smaller site logo.
- It tightens the padding around the site header so it uses space more efficiently. 
(Might need to make sure this doesn't conflict with #45, whichever one gets merged in first.)
---
Before:
After:

Varya: Clean up the header on mobile

---

varya/assets/css/style-woocommerce-rtl.css
varya/assets/css/style-woocommerce.css
varya/assets/sass/components/header/_primary-navigation.scss
varya/assets/sass/vendors/woocommerce/components/_mini-cart.scss
varya/style-rtl.css
varya/style.css

This PR properly centers menu items when they wrap. It also modifies the WooCommerce cart position so that it sits below the main navigation. This looks less awkward in general. 
Before:
After:

Varya: Clean up desktop menu alignment

---

varya/functions.php
varya/header.php
varya/inc/template-functions.php
varya/inc/woocommerce.php

Fixes #60 
Renames the `menu-1` menu location to `primary` so it's a bit more clear. 
(Heads up, after switching to this PR, you'll have to re-assign a menu to this new location)

Varya: Rename "menu-1" to "primary"

---

varya/assets/sass/pages/_posts-and-pages.scss
varya/style-rtl.css
varya/style.css

Fixes #54 
Uses the secondary color (red), and reduces the font and padding size so it's less prominent. Also uses the secondary font, since the  primary one is generally reserved for headings.
Before: 
After:

Varya: Adjust the appearance of the sticky flag

---

varya/inc/woocommerce.php

With the move to JavaScript for the menu in #56, we no longer need the `woocommerce-toggle` checkbox. This PR removes it.

[Varya] Remove WooCommerce cart checkbox

---

varya/assets/sass/blocks/cover/_style.scss
varya/style-rtl.css
varya/style.css

Fixes an issue where left/right aligned cover blocks will spill out of the text column.
Before|After
-----------|-----------
The alignment class for Cover sits directly on the element like this: `.entry-content > .wp-block-cover.alignright/left` element. Other blocks like button or image nest the alignment class like this: `.entry-content > .wp-block-button > .alignright/left`. This means the utility class has to applied differently for each condition. This fix overrides the utility class so the Cover block is treated slightly different but still works as expected as far as the system goes.
- Fixes: #55

Varya: Fix left/right-aligned Cover Block margin issue.

---

varya/functions.php

Hi,
Given this theme is written in HTML5, it should declare HTML5 support for styles and script to avoid using `type` attributes in styles and scripts.
Otherwise, W3C validator will throw a warning because of the `type` element.
This option was introduced in WordPress 5.3. For reference, see:
- https://make.wordpress.org/core/2019/10/15/miscellaneous-developer-focused-changes-in-5-3/
- https://core.trac.wordpress.org/ticket/42804#comment:32

Varya: declare HTML5 scripts and styles support for better compliance with W3C validator

---

varya/assets/css/style-woocommerce-rtl.css
varya/assets/css/style-woocommerce.css
varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/abstracts/_config.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/comments/_comments.scss
varya/assets/sass/vendors/woocommerce/pages/_single-product.scss
varya/style-rtl.css
varya/style.css

This PR removes the `--global--color-border-light` and `--global--color-border-dark` variables from the system and replaces each with the singular `--global--color-border` color variable. 
There were only a few instances of these colors in the theme already. 
- The comment-list border color
- A couple of minor instances of border colors on images in WooCommerce.
Fixes: #57

Varya: Removing light and dark border-color and variables.

---

varya/assets/css/style-editor.css
varya/assets/sass/elements/_media.scss
varya/style-rtl.css
varya/style.css

- Adds the `figcaption` style to the `.wp-caption` and `.wp-caption-text` classes.
- Also removes an empty `figure` selector.
Fixes: #73

Varya: Add TRT caption classes.

---

varya/assets/css/style-woocommerce-rtl.css
varya/assets/css/style-woocommerce.css
varya/assets/sass/components/header/_primary-navigation.scss
varya/assets/sass/vendors/woocommerce/components/_mini-cart.scss
varya/inc/woocommerce.php
varya/style-rtl.css
varya/style.css

This is a slightly different approach to the solution in #63.
- It simplifies the Sass structure so both mobile buttons respond to the `.lock-scrolling` class the same exact way. This means all of menu logic can be in `_primary-navigation.scss` and then the `_mini-cart.scss` only has to have overrides for button positioning and minor design related styles.
- Cleans up the z-index rules so both menus can never be visible at the same time.
- Doesn’t cause the unrelated issue [mentioned here](https://github.com/Automattic/themes-workspace/pull/63#pullrequestreview-391557866) to happen.
- Simplifies some of the common nested Sass selectors in a few places.
Before|After
------------|------------

Varya: Alternative approach to correcting menu animation jump

---

varya/assets/sass/structure/_vertical-margins.scss
varya/header.php
varya/inc/template-functions.php
varya/style-rtl.css
varya/style.css

This PR adjusts the spacing of the site header on small screens. It adds a little space to ensure that the whitespace balance is a little more in line with the way it is on desktop, and it also introduces a little extra top margin if a main navigation exists, so that the logo and tagline appear more centered vertically.
Before: 
Menu|No Menu
----|----
After:
Menu|No Menu
----|----

Varya: Refine mobile heading spacing

---

varya/assets/css/style-editor.css
varya/assets/sass/base/_editor.scss

Use the theme's max-width in the editor

---

varya/assets/sass/elements/_forms.scss
varya/style-rtl.css
varya/style.css

Adjusts the layout of the `.search-form`, which shows up on a 404 page right now or appears when you activate the search widget. #89 
**Before**
**After**

Varya: Adjust search form layout

---

varya/assets/css/style-editor.css
varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/blocks/button/_config.scss
varya/assets/sass/blocks/button/_editor.scss
varya/assets/sass/blocks/button/_style.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/style-rtl.css
varya/style.css

Plugin versions of Gutenberg change button markup inside of the editor. Previously it looked like this: 
```
<div class="wp-block-button"><a class="wp-block-button__link">My button</a></div>
```
Now, the button markup looks like this: 
```
<a class="wp-block-button wp-block-button__link">My button</a>
```
Notice that there's no wrapping div anymore, and that the `wp-block-button__link` class has been relocated up to the same level as `wp-block-button`. As a result, the theme's current button styles do not work get inherited correctly in the editor: 
In order to fix this while still preserving compatibility with older versions of Gutenberg, we need to _only_ target `wp-block-button__link`. This PR makes that change, and gets the editor styles for these buttons working again: 
---
To test, …

Varya: Fix button styles

---

varya/assets/css/style-editor.css
varya/assets/sass/base/_editor.scss
varya/style-rtl.css

Fixes #98. 
I put this in `sass/base/_editor.scss` because it feels related to the base styles of the editor, since this only happens on initial render. 
**Before**
**After**

Varya: Use theme fonts for initial paragraph inserter

---

varya/assets/css/variables.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/pagination/_config.scss
varya/assets/sass/components/pagination/_style.scss
varya/assets/sass/variables.scss
varya/style-rtl.css
varya/style.css

Addresses #87.
I discovered there were unused pagination variables. I'm not sure if these are warranted, but made use of them anyways. cc @allancole in case you were thinking of removing these in the audit. 
**Before**
**After**

Varya: update pagination treatment and utilize existing pagination variables

---

varya/assets/css/style-editor.css
varya/assets/sass/base/_editor.scss

This PR syncs up the link style in the editor with the one used on the front end: 
Before: 
After:

Update link underline in the editor

---

varya/assets/css/style-editor.css
varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/blocks/heading/_config.scss
varya/assets/sass/blocks/heading/_editor.scss
varya/assets/sass/blocks/heading/_style.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/style-rtl.css
varya/style.css

Closes #99
Fixes header line height to match the comps. 
Before: 
After:

Update heading line height

---

varya/assets/css/style-editor.css
varya/assets/sass/blocks/_editor.scss
varya/assets/sass/blocks/_style.scss
varya/assets/sass/blocks/search/_editor.scss
varya/assets/sass/blocks/search/_style.scss
varya/assets/sass/components/widgets/_style.scss
varya/assets/sass/elements/_forms.scss
varya/style-rtl.css
varya/style.css

Addresses #101.
**Before**
Editor | Front End
------------|------------
**After**
Editor | Front End
------------|------------
(h/t @allancole for this cool table markdown formatting)
Some considerations:
- Previously there were no search block styles and all the styling took from `elements/_forms.scss`. I felt it would be better to include block styles for this rather than put them in `_forms.scss`, but it makes a handful of styles redundant. I think this still may be the cleanest solution to support both the widget and the search block. 
- I didn't include a new config for the search block, and borrowed the existing `form` variables.

Varya: Refine the search block styles

---

varya/assets/css/style-editor.css
varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/blocks/quote/_config.scss
varya/assets/sass/blocks/quote/_editor.scss
varya/assets/sass/blocks/quote/_style.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/style-rtl.css
varya/style.css

- Adds line-height and font style variables for large and normal quote block config file
- Sets large quote default line-height to 1.5
Before|After
------------|------------
Fixes: #107

Varya: Fix line height in large quote block.

---

varya/assets/sass/blocks/pullquote/_style.scss
varya/style-rtl.css
varya/style.css

Removes the text-align rules on the frontend so that the frontend matches the editor.
Editor|Frontend Before|Frontend After
------------|------------|------------
Fixes: #120

Varya: Fix pullquote text-alignments.

---

varya/assets/css/style-editor.css
varya/assets/sass/base/_editor.scss
varya/assets/sass/blocks/utilities/_editor.scss

Fixes #104.
**Before**
**After**
The issue of alignments is tricky because they are not handled consistently. Sometimes Gutenberg will add `data-align="left"` or a `.alignleft` class, it just depends on the block.

Fix margins on left and right aligned blocks 

---

varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/abstracts/_config.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/header/_config.scss
varya/assets/sass/components/header/_primary-navigation.scss
varya/style-rtl.css
varya/style.css

The elevation variables in Varya are supposed to progress from least shadow to most shadow. Currently, they do not: 
This PR adjust those values so there is a more natural progression: 
---
It also adjusts the elevation level of the main navigation so that the shadow is a little more refined. 
Before: 
After:

Update Varya Elevation

---

varya/assets/sass/style.scss
varya/readme.txt
varya/style-rtl.css
varya/style.css

This is a first pass at adding a readme.txt file to pass the TRT requirements. I mostly just borrowed copy from the markdown version of this file, but let’s discuss what should actually go in here below. 
Fixes: #74

Varya: Add initial readme.txt to pass TRT requirements.

---

varya/assets/css/style-editor.css
varya/assets/css/variables-editor.css
varya/assets/sass/blocks/_editor.scss
varya/assets/sass/blocks/_style.scss
varya/assets/sass/blocks/navigation/_editor.scss
varya/assets/sass/blocks/navigation/_style.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/variables-editor.scss
varya/style-rtl.css
varya/style.css

Addresses #116.
This PR adds styles to navigation block to match what we have for the primary navigation.
**Front-end**
Before | After
------- | -------
**Editor**
Before | After
------- | -------
A few considerations:
- It only adds a handful of editor styles as the UI for adding nav items is complex.
- I did not replace the icons around nested menus because they are inline SVG elements generated by the block.
- I did not do anything to specifically address the mobile use case, because supporting the ability to add several fullscreen mobile menus via the nav block would require some additional front-end logic. But we may want to revisit this assumption.

Varya: Add nav block styles

---

varya/assets/css/style-editor.css
varya/assets/sass/blocks/utilities/_editor.scss
varya/assets/sass/blocks/utilities/_style.scss
varya/functions.php
varya/style-rtl.css
varya/style.css

Addresses #92, adding a stripe background as a gradient preset. 
We may want to finesse the height of the strip.
Noting that it still encounters this same Gutenberg bug: https://github.com/WordPress/gutenberg/issues/21831.

Add stripe gradient preset (#92)

---

varya/assets/css/style-editor.css
varya/assets/sass/blocks/utilities/_editor.scss
varya/assets/sass/blocks/utilities/_style.scss
varya/functions.php
varya/style-rtl.css
varya/style.css

This PR does the following:
- Replaces gradient preset color values with their respective variables.
- Renames the presets to be color agnostic.
- Checks the `custom_colors_active` theme mod to see if custom colors have been set. (Depends on #113)
This should have no impact on the theme visually.

Varya: Use variables in gradient presets

---

varya/classes/class-varya-custom-colors.php

This PR attempts to fix the following bug, reported by @melchoyce:
We likely did not catch this due to differences in php versions.

Varya: fix custom color class bug

---

varya/assets/css/style-editor.css
varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/blocks/pullquote/_config.scss
varya/assets/sass/blocks/pullquote/_editor.scss
varya/assets/sass/blocks/pullquote/_style.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/style-rtl.css
varya/style.css

This PR creates a pullquote-specific variable to set the letter spacing.
This CSS property is currently tied to the H4 letter spacing, but I think a child theme designer should have control if they don't want those values to be the same.

Varya: Add a letter spacing variable for pullquotes

---

varya/assets/sass/child-theme/style-child-theme.scss
varya/assets/sass/style.scss
varya/readme.txt
varya/style-rtl.css
varya/style.css

Cleans up a few things in the `style.css` header: 
- Changes the author to Automattic
- Removes the "WordPress" text from the `Requires at least` entry.
- Adds the `Tested up to` and `Requires PHP` entires, as per [new requirements](https://make.wordpress.org/themes/2020/05/14/new-required-header-fields-for-style-css/). For the PHP version, I used the [earliest version supported by WP](https://wordpress.org/about/requirements/).

Varya: Update style.css header

---

varya/assets/sass/blocks/quote/_style.scss
varya/style-rtl.css
varya/style.css

This PR addresses a bug that arose recently in how borders and padding was applied on quote blocks. The bug affected the front-end only.
**Before**
**After**

Varya: Fix quote padding and borders

---

varya/assets/sass/components/entry/_post-thumbnail.scss
varya/style-rtl.css
varya/style.css

Closes #136. Makes featured images full-width on single pages, but standard width everywhere else. 
Single page:
Archive page:

Add max-width rules for featured images.

---

varya/assets/css/style-editor.css
varya/assets/sass/blocks/navigation/_editor.scss
varya/assets/sass/blocks/navigation/_style.scss
varya/style-rtl.css
varya/style.css

I think the markup changed in the nav block — our font styles don't seem to work as of Gutenberg 8.1.0. This PR gets them working again. 
Before: 
After:

Varya: Use correct font styles for the nav block.

---

varya/assets/sass/components/comments/_comment-form.scss
varya/style-rtl.css
varya/style.css

This PR makes a minor CSS adjustment so that form fields appear more predictably.
Related to #155.
There should be no visual impact.

Varya: adjust comment form field CSS

---

varya/assets/css/style-woocommerce-rtl.css
varya/assets/css/style-woocommerce.css
varya/assets/sass/vendors/woocommerce/components/_reviews.scss

Assuming #156 makes it in, the `flex-basis` rule added in #155 will be unnecessary. This PR removes that rule. 
To verify, view a WooCommerce comments form and verify that the "Your Rating" stars are showing up on their own line, as they do in the "After" screenshot in #155.

Varya: Remove flex-basis rule from woocommerce comments

---

varya/assets/css/variables-editor.css
varya/assets/css/variables.css
varya/assets/sass/abstracts/_config.scss
varya/assets/sass/child-theme/variables-editor.css
varya/assets/sass/child-theme/variables.css
varya/assets/sass/components/header/_config.scss

This PR makes a minor change to the largest font size used in the theme. 
It changes the largest font size variable from 64px to 48px. This feels pretty natural in scale, and also allows us to have non-ridiculously-sized text on mobile. 
Before|After
---|---
Before|After
---|---
In order to make this work nicely, it also _slightly_ changes the text size for the site header. This used 64px text on desktop before, but now it'll use 60px. The reason for this change is just so that we can get a clean pixel-perfect value through calculation (if we wanted 64px, we'd need to use `calc( 1.33 * var(--heading--font-size-h1) )`, which works out to 63.99px. 😕). 60px looks fine.

Varya: Update xxxl text size

---

seedlet/functions.php

Before, the site logo images were generated at the exact size they were used, which resulted in blurry logos on retina screens. This generates them at double the normal size to fix that. 
Before:
After:

Make site logos crisp on retina screens

---

seedlet/functions.php
seedlet/inc/block-patterns.php

Closes #162 
This PR adds a couple block patterns. In order to avoid the question of where we should host the images that would go in these, it just leaves them as placeholders. Not sure what a better solution should be at this point.

Try adding Seedlet block patterns

---

seedlet/functions.php

This PR does the following: 
- Makes sure theme mods are _not_ empty before choosing default or custom color
- Uses new conditionals in gradient color variables
To test, add and activate Seedlet on a brand new site, visit the editor, and view the colors panels of any block. You should see the full set of default colors appear instead of 6 black colors.
Fixes: #174

Seedlet: Improve custom color conditionals.

---

seedlet/assets/css/style-editor.css
seedlet/assets/css/style-woocommerce-rtl.css
seedlet/assets/css/style-woocommerce.css
seedlet/assets/css/variables-editor.css
seedlet/assets/css/variables.css
seedlet/assets/sass/abstracts/_config.scss
seedlet/assets/sass/blocks/cover/_config.scss
seedlet/assets/sass/blocks/utilities/_editor.scss
seedlet/assets/sass/blocks/utilities/_style.scss
seedlet/assets/sass/child-theme/variables-editor.css
seedlet/assets/sass/child-theme/variables.css
seedlet/assets/sass/vendors/woocommerce/components/_product-tabs.scss
seedlet/assets/sass/vendors/woocommerce/elements/_notices.scss
seedlet/assets/sass/vendors/woocommerce/elements/_tables.scss
seedlet/classes/class-seedlet-custom-colors.php
seedlet/functions.php
seedlet/style-rtl.css
seedlet/style.css

As suggested by @allancole in #175, this PR renames the "Background Light" color and variable to "Tertiary". Note that while testing, you may have content that refers to the old classname. This should be updated to reflect these new changes. (I don't think we need a fallback class, because the theme hasn't actually launched yet).
While I was in there, I also reordered the variables in `class-seedlet-custom-colors.php` so that they make more sense. 
Before|After
---|---

Rename "Background Light" color to "Tertiary"
